# Generated by Django 5.2.4 on 2025-07-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appservice', '0002_alter_cashflow_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
